GROQ_API_KEY = "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"
LANGCHAIN_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyApH8Sk8uPWe1NS0Ie98uDQD3jo89VD_UA"